services:
  web:
    build: .
    container_name: django_web
    environment:
      - DNS=8.8.8.8
    command: >
      gunicorn project_root.wsgi:application 
      --bind 0.0.0.0:8000 
      --timeout 180 
      --workers 3 
      --log-level info
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    ports:
    - "8000:8000"
    env_file:
      - ./project_root/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: gepixelt_db
      POSTGRES_USER: gepixelt_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/



  redis:
    image: redis:7
    container_name: redis_cache_gepixelt_v2  # changed container name
    ports:
      - "6380:6379"

  celery:
    build: .
    container_name: celery_worker_gepixelt_v2 
    command: celery -A project_root worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - ./project_root/.env

  celerybeat:
    build: .
    container_name: celery_beat
    command: celery -A project_root beat --loglevel=info --schedule=/data/celerybeat-schedule
    volumes:
      - ./data:/data 
    depends_on:
      - web
      - redis
    env_file:
      - ./project_root/.env

volumes:
  postgres_data:
  static_volume:
  media_volume:
