# Generated by Django 5.1.7 on 2025-04-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_order_is_order_accepted_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='is_delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='is_paused',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='order_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=20, null=True),
        ),
    ]
