# Generated by Django 5.1.7 on 2025-04-24 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_orderdata_is_cancelled_orderdata_is_delivered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_data',
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='order_items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order_app.orderdata'),
        ),
    ]
