# Generated by Django 5.1.7 on 2025-04-24 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_remove_order_order_data_remove_orderdata_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_data', to='order_app.order'),
        ),
    ]
