# Generated by Django 5.1.7 on 2025-04-24 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_orderdata_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauserequest',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pause_request', to='order_app.order'),
        ),
    ]
