# Generated by Django 5.1.7 on 2025-05-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_alter_pauserequest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='delivery_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
