# Generated by Django 5.1.7 on 2025-05-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_rename_stripe_subscription_id_stripecustomer_default_payment_method_id_and_more'),
        ('products', '0006_remove_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_duration',
            field=models.CharField(blank=True, choices=[('1_month', '1 Month'), ('6_months', '6 Months')], default='1_month', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('delivery_day', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Being Prepared'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='order_app.order')),
                ('products', models.ManyToManyField(through='order_app.DeliveryProduct', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryproduct',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.deliveryschedule'),
        ),
    ]
