# Generated by Django 5.1.7 on 2025-05-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_remove_deliverymanarea_delivery_man_name_and_more'),
        ('order_app', '0013_order_subscription_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryschedule',
            old_name='scheduled_date',
            new_name='delivery_date',
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.area'),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('running', 'Running')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='order_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('running', 'Running')], default='pending', max_length=20, null=True),
        ),
    ]
