# Generated by Django 5.1.7 on 2025-05-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_rename_scheduled_date_deliveryschedule_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
