# Generated by Django 5.1.7 on 2025-05-30 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_stripecustomer_stripe_subscription_id'),
        ('products', '0006_remove_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
