# Generated by Django 5.1.7 on 2025-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0018_alter_deliveryactionrequest_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paused',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
