# Generated by Django 5.1.7 on 2025-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0019_order_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pause_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
