# Generated by Django 5.1.7 on 2025-05-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0020_order_pause_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_subscription_expire',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
