# Generated by Django 5.1.7 on 2025-05-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0021_order_is_subscription_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
