# Generated by Django 5.1.7 on 2025-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('delivery_man', 'Delivery Man'), ('bekary', 'Bekary')], db_index=True, default='user', max_length=100, null=True),
        ),
    ]
