# Generated by Django 5.1.7 on 2025-05-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='trial_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
