# Generated by Django 5.1.7 on 2025-05-17 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_customuser_trial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentForSixMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_status', models.BooleanField(default=False)),
                ('commitment_start_date', models.DateField(auto_now_add=True)),
                ('commitment_end_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
