# Generated by Django 5.1.7 on 2025-05-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_commitmentforsixmonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentforsixmonths',
            name='committed_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commitmentforsixmonths',
            name='commitment_start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
