# Generated by Django 5.1.7 on 2025-04-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('items', models.JSONField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='productbox',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='ProductBox',
        ),
    ]
