# Generated by Django 5.1.7 on 2025-04-30 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_remove_deliverymanarea_delivery_man_name_and_more'),
        ('subscriptions', '0002_box_remove_productbox_ingredients_delete_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBoxRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField()),
                ('date_of_delivery', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('area_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.area')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='subscriptions.box')),
            ],
        ),
    ]
