# Generated by Django 5.1.7 on 2025-04-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_freeboxrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboxrequest',
            name='delivery_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
