# Generated by Django 5.1.7 on 2025-05-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_box_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='country',
        ),
        migrations.RemoveField(
            model_name='box',
            name='price',
        ),
    ]
