# Generated by Django 5.1.7 on 2025-05-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_selling_price'),
        ('subscriptions', '0007_freeboxrequest_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='items',
        ),
        migrations.AddField(
            model_name='box',
            name='items',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
