# Generated by Django 5.2 on 2025-06-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_order_manage', '0003_order_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
