# Generated by Django 5.1.7 on 2025-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_order_manage', '0006_deliveryday_is_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
