# Generated by Django 5.1.7 on 2025-03-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
